### ISSUE TITLE
how to know if the topology was loaded successfully and what to do otherwise

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/topology#163] opened 2023-08-30 17:33 UTC
Hi,

Suppose that your Napp starts after Kytos Topology Napp, and loses the `topology.loaded` event. In this case, how should we know if the topology was loaded ?

If the load topology method fails for some reason, should Kytos restart? Should we try to load again?

**Comment by viniarck** [comment] 2023-08-30 19:03
@italovalcy, 

Theoretically, I won't lose it when NApps are loading, despite each NApp thread start running, due to the core [event handlers asyncio tasks (queue consumers) only get started consuming after all napps are loaded](https://github.com/kytos-ng/kytos/blob/master/kytos/core/controller.py#L350-L364). Nevertheless, here's still room to also make sure all subscribed handlers get subscribed before starting any NApp thread, but still it shouldn't impact. Let me know if you have encountered any issue or if it's just a question. Regarding start-up order, all the rest remain the same, Italo, we're still recommending that all dependencies get start first just so if any request is also made all endpoints will be there. 

> If the load topology method fails for some reason, should Kytos restart? Should we try to load again?

IMO, no, although they all share the same OS process, ideally, [each NApp shouldn't bring down the controller](https://github.com/kytos-ng/kytos/issues/314), if a NApp fail to start or constinously crash ideally it should be unloaded. The issue is still open to discussion, but there's some of the points discussed there. Also, if your Napp depends on a NApp that's misbehaving or sometimes don't start correctly you should file an issue just so it can be handled properly.

**Comment by italovalcy** [comment] 2023-08-30 19:24
@viniarck, thanks for the clarification on the event consumers. It was actually a question, and I'm glad to know that events are queued and they will start being consumed upon all Napps be loaded! 

For the second part of the issue, you are right. I agree with you that a NApp fail should not bring the controller down. However, since the topology holds a higher role for the whole Kytos ecosystem, we should think about strategies to handle fails on the topology load process. What do you think?

**Comment by viniarck** [comment] 2023-08-30 19:45
> We should think about strategies to handle fails on the topology load process. What do you think?

For sure. By default, though, it should never hang or crash, as you've experienced recently with the MongoDB case, once it's reproduced and identified we can also provide a better try catch or somehow set a timeout for this operation or side effect. 

Generally speaking to also provide more control, what we can potentially consider is to also start categorizing if a NApp failing to start is critical or not (and use it as an attribute on kytos.json), if it's not then it's a matter of unloading the NApp, otherwise, the controller would shut itself down, and then the container itself running `kytosd` could try restart it all again depending on its policies. Related to this, since we know the controller controls the main thread, we can also consider implementing a sort of keepalive to confirm that indeed the NApp is reponsive, probably a ping-ping event message. 

These are my initial thoughts, I think it's a large and generic problem to solve for NApps, but for sure we can make progress in that front based on our priorities once it's doable. In the meantime, for the mongodb initialization issue that you encountered, then we can try to provide a specific more reliable initialization. How does that sound?

**Comment by viniarck** [comment] 2023-09-25 20:47
@italovalcy, after thinking more about it holistically, I believe the safest route, indeed, is to for all NApps that fail to load, an unhandled exception during `setup()` execution, then the controller should shut itself down and not only unload the NApp. Initially, I wasn't inclined to generally, have a shutdown for this, but in many cases, an unhanded exception during `setup()` can cause many unexpected issues, most of which are critical for the NApp to work as expected. Let me know if you agree, we'll need this decision for me to enhance https://github.com/kytos-ng/kytos/issues/413, and then properly cover that issue.

**Comment by italovalcy** [comment] 2023-09-26 13:29
> @italovalcy, after thinking more about it holistically, I believe the safest route, indeed, is to for all NApps that fail to load, an unhandled exception during `setup()` execution, then the controller should shut itself down and not only unload the NApp. Initially, I wasn't inclined to generally, have a shutdown for this, but in many cases, an unhanded exception during `setup()` can cause many unexpected issues, most of which are critical for the NApp to work as expected. Let me know if you agree, we'll need this decision for me to enhance [kytos-ng/kytos#413](https://github.com/kytos-ng/kytos/issues/413), and then properly cover that issue.

I agree and support this approach, @viniarck . From my point of view, if a Napp fails to start up correctly (i.e., exception on `setup()`), this can impact the whole Kytos ecosystem, especially other Napps that eventually depend on the faulty one. In that case, it is much easier for the network operator to see that Kytos went down and quickly identify that something is going on, to take further action. If anything, the operator can always disable the Napp manually and start Kytos, but for the system consistency itself, the best approach I think is to shut down the server.

**Comment by viniarck** [comment] 2023-09-28 13:11
Closing this since https://github.com/kytos-ng/kytos/pull/414 has landed. In summary:

If any unhandled exceptions happens during a `setup()` `kytosd` will shutdown and eventually exit the process. 

Also, `maxTimeMS` timeout was parametrized by default for index creation, that ended up hanging in a particular situation, so that now is retried and then eventually will raise an exception, and if it's not handled it'll fall in the previous case of unhandled exception on `setup()`

**Closed by viniarck** 2023-09-28 13:11 UTC
Labels: question
